### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by onurgamgam** [suoto/vim-hdl#44]
Hi, vim-hdl tool seems to be perfect and I am very excited to try it.  When starting vim with a vhd file, following error is reported.

Error detected while processing function vimhdl#setup[10]..<SNR>59_startServer[6]..<SNR>59_pyEval:
line   4:
Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "D:\programs\gVimPortable\App\vim\plugins\vim-hdl-master\python\vimhdl\vim_client.py", line 100, in startServer
      self._startServerProcess()
...
...
...

My setup is as follows:
 - Windows, 
 - python3.7 64 bits.
 - No internet connection

I installed hdlcc package to python. In anaconda prompt, when hdlcc is run, hdlcc server starts to run.

To install vim-hdl, the zip file of the repository is extracted and the following code is added to vimrc.

set runtimepath+=$VIM\plugins\vim-hdl-master

I checked previous issues and realized that there was no Windows support (by March 26,2018). 

My questions are

- Is there a support for windows now?
- If yes, what would you suggest me to solve it? 

Thank you for your time.

**Comment by suoto** [comment]
As of now, vim-hdl might work on Windows, but since it's not tested against, so I can't really guarantee it.

In any case, vim-hdl depends on specific versions of hdlcc bundled as a submodule but they're not copied along with the repo zip file. You might want to try cloning the repo with `git clone --recurse-submodules https://github.com/suoto/vim-hdl` and then moving the resulting vim-hdl folder to where you like.

Other than that, runtime seems correct given that Vim issues that error message.

**Comment by suoto** [comment]
vim-hdl is a client for [suoto/hdl_checker](https://github.com/suoto/hdl_checker) (in fact, it was the very first client), but HDL Checker now also supports [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (which is a "generic" type of client).

Any tool supporting LSP should interact with HDL Checker the same way and benefit from what vim-hdl offers. I've been using [dense-analysis/ale](https://github.com/dense-analysis/ale) (it also works on Windows) and opened [this PR](https://github.com/dense-analysis/ale/pull/2804) to add out of the box support for HDL Checker to it.

A more comprehensive list of tools supporting LSP can be found at https://microsoft.github.io/language-server-protocol/implementors/tools/
